default: &default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4

development: &development
  <<: *default
  username: root
  database: lobsters_dev

test:
  <<: *development
  database: lobsters_test
  <% if ENV['CI'] %>
  host: 127.0.0.1
  port: <%= ENV['DB_PORT'] %>
  <% end %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
