default: &default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4

development: &development
  <<: *default
  username: root
  database: lobsters_dev

test:
  <<: *development
  database: lobsters_test

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
